### ISSUE TITLE
comments on the schematic and PCB

### ISSUE THREAD

**Issue by tenbaht** [roybaer/sduino_uno#1]
This looks amazing! I am looking forward to see the first prototypes!

Looking at the schematic I would like to comment on the hardware:
- to initially program a serial bootloader it would be very handy to have a ST-Link compatible 4-pin SWIM connector. I suggest using the same pinout as used for the stm8sblue PCB: RST, GND, SWIM, MCUVCC
- The serial connection between the CH340 and the CPU looks weired to me. Really through the LEDs? Maybe the pins RN2-2 and RN2-3 are supposed to connect to MCUVCC and the IO0/RX and IO1/TX labels should be connected to RN3-7 and RN3-8?
- it might be useful to be able to open the connection between CH340/TXD and STM8/RxD in case the pin is used as an output pin. Solderbridge? Jumper?
- Does J2 really connects to RESET two times? Maybe RESET and GND?
- I am not sure if Q1 is always guaranteed to connect USBVCC to +5V if UIN is not present. U5 is not powered before Q1 is active, but Q1 can't be active before U5A outputs a valid signal. Possible deadlock? Maybe use the unused resistor RN1/3-6 to pull Q1/G to GND?

If you are planning to develop this design further into a commercial product it might be worth to:
- add decoupling filters to VBUS and DC to reduce EM emissions (ferrite beards 220r@100MHz and 1nF+100nF capacitors)
- additional ESD protection on the USB port might be useful

general:

- for people not familiar with kicad it might be convenient to add the schematic as pdf to the repository

PCB:
- a GND guard ring from pin 4 around Y2 and the clock signals would help **a lot** with the EM values.
- the via for SCL under Y2 might connect to the crystal housing after assembly
- SDA is a very sensible signal, but it is routed right under Y2, even on the top side. Might cause malfunctions in I2C communication later.
- rearrage C1, C2 and Y1 is in [Atmel application note AVR186](http://www.atmel.com/Images/Atmel-8128-Best-Practices-for-the-PCB-Layout-of-Oscillators_ApplicationNote_AVR186.pdf)

IMHO it would be worth the effort to move Y2 closer to the CPU and get the I2C signals out of the way. It might help to use a smaller cyrstal. E.g. the [FA-238 series in size 3225](https://www.digikey.com/product-detail/en/epson/FA-238-16.0000MB-C3/SER3686TR-ND/2403378). The price difference to a HC49-type is only a few cents. Resonators with integrated capacitors are another option, e.g. [AVX PRQC series](https://www.digikey.com/product-detail/en/avx-corp-kyocera-corp/PRQC16.00CR5010X000/1253-1675-1-ND/5870331) or [Abracon AWSCR series](https://www.digikey.com/product-detail/en/abracon-llc/AWSCR-16.00CV-T/535-10008-1-ND/2001631)

**Comment by roybaer** [comment]
Thanks for the constructive comments!  I appreciate them a lot.

In order:
- The STM8S105 devices, among others, have an integrated ROM bootloader that briefly listens for programming data on all UART and SPI ports, provided that the program flash is empty or the respective option byte is set.  SWIM programming should therefore never be needed, except for mishaps where the bootloader enable option has accidentally been disabled.  In that case the board can still be flashed via jumper wires.  I therefore chose to omit a dedicated SWIM header.
- Damnit!  Thanks a lot!  Of course it is supposed to connect the way you pointed out.
- Neither the Arduinos nor their clones have that, but I'll take it into consideration.
- Yes, J2 just replaces the solder bridge found on the Arduino.  You can cut the reset line on the bottom side where the arrows are and solder on a jumper header.  That way J1 and J2 can be left unpopulated by default.
- That part of the circuit has been taken from the Arduino reference design without modification, so I consider it well tested.

The USB to CH340G wiring is taken from the CH340G application notes and is largely identical to that found on the (admittedly CE-less) Arduino clones.  So for now (10 piece prototype run), I'd consider additional EMC and ESD measures unnecessary gold plating.

Concerning PDFs:  I might upload PDFs once I have working boards.  No need to spam the git history.

PCB:
- There already is a GND ring around Y2, C5, C6, D2, C11 and C4 that connects to pin 4.  It goes through half a dozen VIAs but should be better than nothing.
- The VIA should be below the solder mask.
- The placement of the I2C lines is clearly not optimal, indeed.  It was the best routing I could come up with, though.  Let's hope that possible 16MHz interference does not harm the 100kHz signal too much.  If it does, one might have to switch to the internal 16MHz resonator.
- Maybe I'll flip C2.  There is not much more I can do without starting over.

I did consider using a smaller resonator.  Most of them look next to impossible to hand-solder, though.  That is why I went for the common HC49-THT type.  They are also much cheaper (in volume) and easier to source.

And once again thank you for pointing out that major TX/RX brain fart!  That could have resulted in a great deal of disappointment and frustration.

**Comment by tenbaht** [comment]
Ok, that all makes sense. I wasn't aware of the build-in bootloader. Hopefully, we will not miss the SWIM connector more often then expected.

I just added support for this proposed pin mapping in the new [experimental branch of sduino](https://github.com/tenbaht/sduino/tree/experimental), but since I don't have any similar CPU it is completely untested. Feedback would be highly appreciated!

**Comment by roybaer** [comment]
I think we can close this.
